# Generated by Django 2.1.7 on 2019-03-07 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-title']},
        ),
    ]
