# Generated by Django 2.1.7 on 2019-03-13 03:29

import book.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('publisher', models.CharField(max_length=50, validators=[book.models.min_length10_validator])),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('ip', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('photo2', models.ImageField(blank=True, upload_to='book')),
                ('photo3', models.ImageField(blank=True, upload_to='book/%Y/%m/%d')),
            ],
        ),
    ]
