# Generated by Django 2.1.7 on 2019-03-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, upload_to='book/img'),
        ),
    ]
